### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by irkingmaker** [dnellur4/flood_detection_model#73]
please add documentation generators

**Comment by svengal03** [comment]
added the pdoc.yml file.
deploy failed in the main 
commit #78 
please check @dnellur4 
<img width="946" alt="Screen Shot 2022-10-07 at 7 29 20 PM" src="https://user-images.githubusercontent.com/112122632/194675164-e258169d-2c35-4832-8b3d-f31954a9dbf1.png">

**Comment by svengal03** [comment]
documentation generators are working now
